# Copyright 2021 ZestBloom Inc
# See LICENSE file for licensing details.
options:
  algo_net:
    default: "mainnet"
    description: |
      Specifies the network on which to configure the Algo node.
      Select from [mainnet, testnet, betanet]
    type: string
  install_source: 
    default: "deb https://releases.algorand.com/deb/ stable main"
    description: |
      Source URL for Algorand deb repo.
    type: string
  install_key:
    default:
      -----BEGIN PGP PUBLIC KEY BLOCK-----

      mQGNBFz/pAIBDADXyIjyU4pjcyTelWUBoqLHgBp0aACFFZdvm/86t5BSGpqVdQmS
      sxg2s5QfChcmWbBnScTI61ojyDPXDEyelUgjXu5p2Ujz4QWLizlAyUGt9P7fHwkB
      RR6cYNFtp2xztVHE00aLMbwbmdpv8tbMbBZDgUW0gTYT1Ha17baBBKQL/u+RypOx
      fPRwNsnwJ8rZVJYgHqkOc49rL1t2aCdWztXs54Bdd0j39B2NBdd6WGjaOwdkp10s
      xrsKCAyDQg/XU2G30ypAxa7zueIqvPkW27dKc4W9juUzoiRNUepUuChfVM+uwkF4
      IHjZvB3II4n0+SLLnw8kovEdQtbDZSc78Lj9bF/5Q1cJR3lTG2gGV69UWO/kKRER
      mqxjGRjQZrJ5wScLtnZ9aDAJ+HLNSXh/eE+zBynMcF2VBEwFRsYjmxRvu063ZKdl
      n+yANmGG8kcjc2lrx4f+mEth/i0BNpUJYJl0Y4Yh1QP1hAo8C7w1tfqKsKD5z/UJ
      5mhozyw0l87JU/sAEQEAAbQmQWxnb3JhbmQgZGV2ZWxvcGVycyA8ZGV2QGFsZ29y
      YW5kLmNvbT6JAc4EEwEKADgWIQRhHelKOW8BNZxyr1btrNKdoQpOpgUCXP+kAgIb
      AwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAKCRDtrNKdoQpOpmyGC/0eQrg0lYNz
      7OWRBjgvvMtL9uODxXRc7C2tMzIwlqaJ/ZqCYimLbwDg9RJSdCFa9EYIpbXn9Dsz
      6wjiyRd4TQuEom10b2CY5Pm/FJB5p/LHctdSSb3IM0kDaQSmfo8wW7aTdlwOYexz
      zSI2MzNYt4HWEkjp5MJbmGZSuGPRWI2OL1irDJUvphoK6pvFYUeocTsufHi46ZOl
      4T9s8+9EWv8jPPiIXAGmUbK3cNXvwGTe+rmEBwXC3l864x1X/bDVG9ZbAOJRolje
      IKUhdqh7DAWj1NVwx+KPGfqZIdeNDz2ATf9ZEWAbYRKhd6C6tbMIU9rXrpMPnFKk
      Q7+EXh+lH2BgMcatnnIrBfj9bdnUHpisA+cWkIL7XwpQVTHv/uyeORqFL632/Z+B
      WkSjs+fO72umzXQUh6x7q/B8emaKrljE6L7C1BLfJJnKz4+jTRwSo5EJS6oW6eda
      ZpUuJm+VTA6NTcJs4+WlqFe+pZQeslZLom1S1H6m6czyTV7Z/zXNc7q5AY0EXP+k
      AgEMAN/JndhoZAdKqFzBBh/P1an9c2LHeG70fLFAEplgkB0ndmqQQYtZqAshOVO4
      8KEuEYJnugj4/NSUgJUcUwq5E+rrC8r2ZIYm1vW95NaeAzXpMvDVZ414GYuUXpSu
      oMoF+VAJn+hkilLpvAQFGvsvE70BokIQiDp2s5bZpvQFScH+nUlDl3plG6hWjmDU
      VNRx6YPCrFTScB+8Ap585dOIqlkWZIyqn89l2K+ceetMfjUyIlaWO+VkTxaHIAt6
      prPN8UrAy6vZmyFMZZrI1+/9U0JaHRrogSIE4lrJqdbz+wfX7UPepUR/DJUpNwFc
      eKnPb7fwkJEC2DfCpsRcX1jgB4vYhhDgh6X0qdvNr8udc0uWoHGmUzO/WeRdHVBG
      4twTnscxbViMA0skH6J/F4Y8qm1KQ6rQjO0duKNYvyFjDpx1tpX7bburKMMK1Zo8
      lZSL7ZD0PIO2RrURK1tecIZP9TaP1qCvhKdR4xW8OzGhO/cPdNAaC5t5qdGW/FtL
      Eh6/SQARAQABiQG2BBgBCgAgFiEEYR3pSjlvATWccq9W7azSnaEKTqYFAlz/pAIC
      GwwACgkQ7azSnaEKTqb4dQv+KY80JMfxOBYOj1VM31Zc67T/C8nD7M3qI3ylkXf8
      eK3vi8DRUaBbz50b8zWadTW2ohUe3PQJoheRUQyVFQbO2BiD+qxkmxUJ71jXW5Fq
      cB3hcx1BFePkWz1IlsVdTFtVPJVyBCnOFz+zQwBD9pX1lBoVtK9Wh/7jUaWoc6h3
      mXEWHREnJwrdAcxYVSZuiZEBAvESjpe61KaCiacTquxbOIPPPjt08jQzE3SciRKM
      wWqp/mvx3hWWFTI5lMvppeEKaNb/C/NTmheVJnt25O8v7Y1KA8ENWnBltmgEcQe9
      tU86vZ2nagtJW03Rj+AYTQzg7MeHis+iWlOGYlTtev4hVz4Lmiv2LoMjhK7lpAth
      u6MtcPKxP/nC9se4m2lO86711qPkgS/f9Rcp7vlwcThr9lOtiIRj5e2afapSzeh1
      QdLcO25IFC2J1ed9S+GD2uBxFRDB/D8Pr3J5jvUUCeaYnVhCRrWqN+1tGhHUedDe
      yVjCxLOgqpmA0uZgGnpmTPpBuQGNBFz/qNkBDADAjrCex5F5tnfmAmPL2j3G/bAY
      4d4g3ybGnsX0AzLmiBJ+X54wxtPLHRwFWr04yD6B9dzMln4S3yuYIkj1tfuSIuu3
      DifbwDOixPNK7yFuFD14Or4n9d1ehN8KexIXmgnFu1cPHecglEihtK2TzvycN6J/
      ri2xcGnTEQFgQoCIohiSK53tj/+BXZS6LyQCek8Zdm9dBJm2Ed796sjIlxXOhqbI
      g+GP7VksIIgLVdHmbvrPLdZrKiXrmBxpEmWBILSWPslDwkobpC+Q9V6jUE+qjypF
      /Dut4PB8F+7iK+VZaEmsdNx6HjkQdgLcFDwhzb2UjDlO+EmWdBZb2gCmrUQIbSmh
      gXIgIa2n0U+qQrWYkRUXSD130mPzIK2dvysO4eKYuikNOwUw/0EIfg+GWus7ISnx
      eDehopTffxVdQovSXckMAgXbf/zrr4LmPOTl0v3q6V7cpmG/Up4HB4dEzn4zclo0
      Lfd2c6slsM4D/pX53j/hvgh5ddKystSl2lO7OzsAEQEAAYkBtgQoAQoAIBYhBGEd
      6Uo5bwE1nHKvVu2s0p2hCk6mBQJd1VrOAh0BAAoJEO2s0p2hCk6mcR8MANXmZUXc
      xX13SHNpBVd+SxrzVJh73SVP+WqIFKhbATFgUQuE/0FDfl5hnxMjosT8hulpZ3TE
      Pte8XOFlCrFmz/DpvPmSBVa/GutJ4sA3YYhW1F7Kc1EOQBYqq4gXLvNb7jJ3mO27
      pZqObixaBHTUCn0kDL7R5yuBGBSf9O7LCq70iD5avdTWMYOv9dOF8BVzvjUpEo7B
      qGilAHjxbDhXobI+yj1s4z7WUKv2bkZAQPw7f6/F5gZ2Dp2j7LkpX6fXlTqGQwM+
      TBZXHHpEtcSsssl5KXmpWlzHAdQ4kd6jkQ1WQB2Hmc4NafcwCGjqO5pO4eh6bTXO
      QcavX0700OZWThrzOw4K3yyrSO91kQPnDrgOPTPSTuMOcKkU6P4U04vV7B5hbRWd
      RPZdTRSRdCmhKINJXljDngemp8MqRqlSj8Miq/QWAgcVZsdUmE9YBnhEiYAyVc4b
      lFGdH7z1CkX9A/qk1YMZyu6FG8q0Ay9SE+y5UlOh+lG7nMAcW5370oUC4YkDcgQY
      AQoAJhYhBGEd6Uo5bwE1nHKvVu2s0p2hCk6mBQJc/6jZAhsCBQkDwmcAAcAJEO2s
      0p2hCk6mwPQgBBkBCgAdFiEE8usQMbz1qT5q5sJ+GUfcABZXaNIFAlz/qNkACgkQ
      GUfcABZXaNLUewv+IHfJMcq8AXc6po4jHdeD8w5pqkluw3LL9Zr/dwrr5J5ej+ev
      9dr365GPMWxi3hZMNWCvalk5lpen2lIBpBbIYnCpsS3VLczk9g3xBJbHuIYC+as7
      q2eEXS+Ei2HJO4x6m9jkCb0YqMkfTsQPiqr5rXgNqPFX79b5e8awU/f/ldJEJFMP
      fHXvQsP5skqFczIjwgms1p84PAUrPAWE7RzQEpe0f9dsuXtwOTE6r54TGThpxbZl
      KPlD2ij9nDqfgFNFTaRFEa2fCEODzVZkIRtYtg2oOn8fc6PqY8U+aEWYC98QO0d4
      Rzs+EgRu7KgJFdJEbb8YntZzNaCZt72+ilR9qA4AX6/ehfbROYlAib/oY14NdMJS
      ksVDgNVrKWnZDkEwHB0Jdkm00glNNcTbQnYHWKHn3LIngAhKDQa00/axgvqZxmzs
      es2RsCVgRtAuOjWz4qO2qSwbwEYcul/JCWRn2BA8Bm5cFmUPv8dzROJw6AdUp0IQ
      NCIncy6W+jShAH5iwn8L+wU5GuY2t1cNuyWxH4g37wdsL/LI2qcoZEKoMjh9cQAV
      uBOukcAR1KIuxxUC9FWvfrJhCaPdt45WYPS4gSGI1GAbH4LwDW8gPV7FmEkSmzXX
      mOhKxjtAGx7DM8vMq6hqRhK8vWMfoQyL4MTDtiJKeBXKYmILNx5hBgMy9T9nMBA4
      vCNFfQB+1+OudpHOuTApBpGX+nF38zOV0LhRtOyukL9UKG3XIH0weWPBNHOLAtj4
      GwXA2MuPWgsVadBgAHd/nEJtnF+kj4P79DulPtpyoHEY8z8Ee51mulyFllcQvlv0
      cDFhXme2b1MprErIeRO5VQq0+luOOtxujybeXfOmrhTQlDaDCeI1MUQLmwFHi5GD
      4VuLGD2da+jR512tRd5lBFOOQgeq/B9ffvIf/I6uXAqJdIllmkTWkAbQWCFbgt4f
      KKaZJOcCdEQ0/q8+bDDMCHVuVuM1zmy+Z7PR6VMBFMcI8XAwUIaNAMpAADtqKXAv
      q+iQgilTp9DBoCU73hn6+7kBjQRc/6mWAQwA35SzNifCKFWb+iX+OcPj3h4FTlHW
      55zrSvJLhnTGSARz9odxzVCzq3JYS4VsTNAHmdXr2TV+Gs4HsU1IZzX5fs7N+rA8
      qi/eOyctEZjmZS0+U3fseofh00N6vwNSU3CIRcLQvJy7XvoTFGQ7n6QZ000SHMUk
      H9Hf3A9dHmcJmYHXHl24CSlzik0FkxGhN+yGIpn6eh+caAG2x559q+lWq5fh6OyM
      pdkD73Y+2ybSc1FYUopzaf1XOACRvi9qOQE5gq9RVdoqDecTB3LEmCEAxCKir074
      MvbLNBgFUo/JQYoJJOgsIGjyTvP2PhySpt/AeYTG5hBI7dOjvt0oDBGT4IA+8CDy
      57N2yx8MxdNOH0oe+8CUZh3RK0wZsVpamKAViRpYkXFFHbnphsGXDo/LrzoWHAKd
      k3+rPknNSSrmu8l+UUf7ZV771B7JYrmXHpZh2eZyNKtqqPr4lSgTdOEsj2IBpeNx
      /EgE7chE/FsPumOR60fQPH3o6ndbbjuVIb/VABEBAAGJAbYEKAEKACAWIQRhHelK
      OW8BNZxyr1btrNKdoQpOpgUCXdVa5AIdAQAKCRDtrNKdoQpOpsELC/9AmjdhWOOA
      /BvDzvwLxtc60IDrbk5Gn/5w8ulOIgzLbnc3ROQstsPK2BnavZ6y2PBkAnWjtWTo
      4Yax9cfemFaxEK2gXV5aGItoqbNrfswiALzYNQhwDFrydwj7wbrOHdk/KVsR53C4
      bY8LsRaCR4DIfCxNza/yOdtqiU29O9zVAtwWuENX1WiH0fyPiWIydhx15SWGpFyU
      ZR0VkG75GUn1mREzitpqelcGV7hDgRfdndMlqywfixObx+Tq8DVajLEuf6p4CKYE
      ectsOAZHa5u5Hg6TS2XXIdOix1GpaMBi61RpvrwJNvUnGmfb1xTn2FFCy5euCrA+
      qHiPxjdWFKtN4pJm+87gxNn4qrFqZIxb3+6LsejhmFYxiWtyCePA15fx+SFmFbqA
      8aYK93irjzLeJ5twmbuBsHhelL2I7GEnFsii5s0U3w7BdWA5klcr0p1QIEum5sF5
      UFQPeM8zR2LWLOnmnsM1q3Z8aPEDpIDjyAdI6B9IK9GLQDf+pFDfS3eJAbwEGAEK
      ACYWIQRhHelKOW8BNZxyr1btrNKdoQpOpgUCXP+plgIbDAUJA8JnAAAKCRDtrNKd
      oQpOprafC/9GWT0iAfhOL9y56W34EaWHpUZTbTWOtKJzmf6T2s3Sz7zozB/GnGFR
      /92hrfKRDx1YhGabthbwhepu/gkkhvkHYv+IhNA+Wt0BcvXmcDFwjH88W88vupjd
      Xc4EU9eyx+0JI17M6/GrBGOwWDUX9ok+dAW/RW5pReBTYZy2Q+TCrBvDHRRha2SA
      k2nQXGshHgUDD8XOp7HmG69s20kAFOWLVSgBexelLPmF/NMpOLHUSW3zF4Ca+C6v
      H62Ob78ANf3Wytvz5mgIq47jiZxOhKorukl1m3jJ+IaXamXsPvF37D5wBnA/JRYR
      XzHTK3LpZsJmbV5zjb0a2yZA16KXscwl8VLpr7NmwywM+rgaGNtN5WEUw2KA69O+
      IeLydBsVBJCbSDCGaS1a4NDawAkN3cg1XMoDNO5+kRr4C9Nj7A8LOYBIFQezfqPj
      GP6cbAnbhdefM1QRc9IvW75ZyH2U78m7vGV5jf5FqKUrytzNYmcqWruiNMHDonGl
      zaqpmq5K3H+5AY0EXdVa9QEMANbgzZfwyUaEQXgwMZ1LrURpMHjOrqAZjwb9QNmv
      CI/s0j4yYw+7PC14iYnrfc7NFzqjBFgRa5RVwgcYJ17CSXIYXUC9xKbeYx3fDVFE
      PrPFVGHg/cEbZ9/gdoj+2Pm3nSfPD5D+nDdCFT46VZgprL1D372l2sIDm5Ty00Su
      VjRlhq/fesCLacOnrwvOTMRGVnBdz6b31HofgjCy8ZslRGjf4ybAShmHCgkirn/L
      nkHq33KTCKRzisDYrATxDW5YTzClovFMmNHyCN1dEdAkMrBbseI6FPVs2Mh4x8ek
      28IkkqqaXM2AmhlGJOsDarJQx2IRd1NUfsWcWGcj409HcvdosQe2c7BrafF3slkx
      uTst6K8Aast24QRqrFiOQcfgTE3L2Gnj53YlCR837NGUgp87gxtBNBbJSoYKDxS+
      WG0xsh57kEMG6eel2g72x6/F25/dhl3ex8533bzBrftM+CHtY/xCTJILQd5bV2WJ
      kb8QijgmbI3p1Xxh5jpDWcwxVQARAQABiQNyBBgBCgAmFiEEYR3pSjlvATWccq9W
      7azSnaEKTqYFAl3VWvUCGwIFCQPCZwABwAkQ7azSnaEKTqbA9CAEGQEKAB0WIQRM
      PszN9oecgNHVlEsDS62rs+N11AUCXdVa9QAKCRADS62rs+N11B5YC/0axhuwKwIi
      FLp8bNd3iOFRqhFpAhkpI9Jji3YYfDYvpIt0LigPISryWuP7u5K1n72GzXzhaPJK
      SPEpyhzMrNCuJndRiX0ZLN1DKZq3iCEUOsUtFPcxhKgvCZzZoLkukz0aS3mENeUj
      U9TfGKPGPtySVj9KMIoUuZ5kFrKeFmQS5crU+7+Q486IpnydqrO+HAn73pg9nMgt
      8YYbTYflWKIYdDsgqIrbw6tahFeFweZScl5tmqgSozrDPRb5rT6a/Z17xQ00ffAC
      isqoLzWr7HdJrjGFZvouUZc7pVviW9QQJPbplGM9nHFjoDtLcCD6AxZpU8II07Hz
      iu+lcKIqTivnIVXqtbH8gJe/zVyCuHYYenayg4IxM/jmWTbVfz/11wCzT0MS+Hed
      3UlP5gufjII96LD1X/mF54+SVADIXZtXBxdKpxZuvA0XmaKVq5TyJtn6Xcvcfiuu
      ZNo1YfbGluGaBDicvfmbLUPATnRBzOlBx4FOEDDxPl9piAKGWGtzVsgKQQwAiCWF
      ldPuLkwj1TlJnOeF3XbjPtZfGpaXP7lRK3vfk6iehlPgtMVgNNvdzK3hylsSxnlQ
      eYg1T1oAiXSqeifWNvExrECzKZCZLP5q0Ms67IXCfMNup1EAUFIAGo8uyxo7cb+y
      2n50sbmr8RgXCfu9CUxxn4d6xOAl9hKhmK78lWkmw5GdkVDz3yRNgaq/co+RlBkW
      Nipi3CaHy+as8nPIEvafMfqpnU5XYVw4Bk7Vi0ma3kf1ZTxjvCdgVYimHvDTuKjf
      a+K7HemOBOzKTdLEFdlmOFzro8DOTFZ5t57RDxhlBqfmkM8V1Wc3YRuY3/1bp6HJ
      3j27X8KWypy8AJAXjMTQkiQCSVi6zctAxx88Ow8P9DaFXOaRFwrsrJtx5xja7mMH
      /hIlVhLxxYcYXSKxpKnP7p15B1XmlTEjE4Sj4cmwSpWOZETOiIZ9/uegOtDcIX0m
      GWN8YExXZ2sqg2t1AkDi8uOfLxAmaN5qJZ5lG2SQgLumiNxNtp9HP74sWgyKuQGN
      BF3VW5ABDADLxQyomJxRFVofKoolzClecmvKG54sx0l3g9BcYHVU8mZzghkxJa+6
      4ikKNMKlVdXMwMiCd7WIDbY2djrnSU27I8ObtH8IJU4jd6IB31sLZ8QiuzKbzWLj
      5HEn6pG1Ql9dTywRfxQIsZMRXLhZ3HdBqO+SB78cMWk7uUZ3tgTaNDOc6CAtgQyc
      HNuYO+wasbyodt1QSPjfOyz3QfuB9cK0FtrP1mrVwVqLIOROawqUX9Yef+Z5QgdH
      A1EHn3YYuNgLqYlj5rGyybOJJC4xjpo6AlPFvFM/KCkjbHO4E5YnHe+d7B7f5rQf
      AImeAdLD7l/T7PgOaOHGRV7LFLY1SbgdUZfdvN/bDBQba7gYEUNs/1i0cOnIM8dK
      kRX4mKtQ1DcYP1t7tuEwu3nnvKniZL6tED4CtdtIBJa7dWqvKwCUQ3uVOGXB12E5
      sXg3g9Rj7etZRnxZxj7MXcjuoLTzVp1eUpy3Ppj31oWoBw2WECjV2IVBxj/oFboN
      hszOMdyeiNEAEQEAAYkBvAQYAQoAJhYhBGEd6Uo5bwE1nHKvVu2s0p2hCk6mBQJd
      1VuQAhsMBQkDwmcAAAoJEO2s0p2hCk6mzH8MAKdRvhirJFt7Cmirzwj0abRUenAc
      Pe5CofpmfT06kfo6COlC/PvI8mp5zryIdL7NucFVLY+GoC1B47qDo9VFnFro/STV
      Rg/93coadrMe7jvrjxyD2wvzFPjWNPeDbT/ss+aLhMlrG4YZGII/6T7OpwODLoYu
      1WJ+AxD8TX7SkhIGNXp3Cdc6Hm5IvvbkXX5gdd+vfFC1lxJ3/UuUBDUIwqCh85iD
      Gj45VcDO8oGIc0sr3OGtpR3nhCvwW9PPQaW2oL8IQZ1Dgj4pT1Wp1qh07GwB71wj
      OIRxpD2WP7QHfYMsrjup7+/OSHD0db4a67C2Qhxk5LaBpuPd459uJ041QjdXhVkO
      EjoZCxN/iXf8goyJaQ2xA14viT3vVoBiyo2TMmsmH+/Ac2o/zEuQWZv4aUWgqocV
      x//QsxwNiypFojU3Les30E9m3hCGrx2uF9qHilPTxNY6f9ib6x5Flxdm5BL1Pek0
      C5h2Jab2OE/t3CmgqydDWM2VTyRvobOBzEbpew==
      =1ZCn
      -----END PGP PUBLIC KEY BLOCK-----
    type: string
    description: |
      Public Repo Key found here: "https://releases.algorand.com/key.pub"
  AnnounceParticipationKey:
    default: "true"
    description: |
      Specifies that this node should announce its participation key (with the
      largest stake) to its gossip peers, allowing peers to prioritize our
      connection.
    type: string
  Archival:
    default: "false"
    description: |
      When true, the node is configured as an Archival node. Archival nodes
      retain a full copy of the ledger (blockchain). Non-Archival nodes will
      delete old blocks and only retain what's need to properly validate
      blockchain messages (currently the last 1000 blocks).
    type: string
  BaseLoggerDebugLevel:
    default: 4
    description: |
      Specifies the logging level for algod (node.log). The levels range from 0
      (critical error / silent) to 5 (debug / verbose). This setting is
      currently ignored. In the future, it will default to 4 (‘Info’ - fairly
      verbose).
    type: int
  EnableDeveloperAPI:
    default: "false"
    description: |
      EnableDeveloperAPI enables teal/compile, teal/dryrun API endpoints. This
      functionality is disabled by default.
